### ISSUE TITLE
get timestamp in milliseconds

### ISSUE THREAD

**Issue by deleteLater** [feature-flags-co/ffc-go-sdk#1]
https://github.com/feature-flags-co/ffc-go-sdk/blob/06084eb9a0f9f423bf37df0037d052aba137a36c/utils/utils.go#L29

the time struct has a method called `UnixMilli`  to get timestamp in milliseconds directly, see [doc](https://pkg.go.dev/time#UnixMilli)

**Comment by bradzhang717** [comment]
UnixMilli function begin with go 1.17， but we are using version 1.16.

**Comment by deleteLater** [comment]
go 1.16 version is the most used version today, so we decide to not upgrade it for now.
