### ISSUE TITLE
`ffc_client.evaluateInternal` logic error

### ISSUE THREAD

**Issue by deleteLater** [feature-flags-co/ffc-go-sdk#12]
https://github.com/feature-flags-co/ffc-go-sdk/blob/f0961ddb8f1428bf7053fc0511378e330904e2d0/ffc/ffc_client.go#L384-L390

when `checkType` is true, we need to check if `evaResult.Value` has the same type as `defaultValue`. see java sdk logic:

```java
if (checkType && !res.checkType(defaultValue)) {
    Loggers.EVALUATION.warn("FFC JAVA SDK: evaluation result {} didn't matched expected type ", res.getValue());
    return Evaluator.EvalResult.error(defaultValue.toString(), REASON_WRONG_TYPE, res.getKeyName(), res.getName());
}
```

**Comment by bradzhang717** [comment]
if checkType && !evaResult.CheckType(defaultValue) {
		log.Printf("FFC GO SDK:evaluation result %s didn't matched expected type ", evaResult.Value)
		data.ErrorWithDefaultValue(utils.GetString(defaultValue),
			model.EvaReasonWrongType,
			evaResult.KeyName,
			evaResult.Name)
	}
