### ISSUE TITLE
built-in properties are ignored when get user property by property name

### ISSUE THREAD

**Issue by deleteLater** [feature-flags-co/ffc-go-sdk#2]
we return user custom property directly when get user property.
https://github.com/feature-flags-co/ffc-go-sdk/blob/1d5258c95d6165463d4a2df9527de373235569a7/model/ffcuser.go#L68-L74

while in java sdk we do consider user built-in property

https://github.com/feature-flags-co/ffc-java-sdk-commons/blob/c0fda46b61f40bd2a61c5203081c817ebd983c86/src/main/java/co/featureflags/commons/model/FFCUser.java#L141-L154

**Comment by bradzhang717** [comment]
fixed, 
https://github.com/feature-flags-co/ffc-go-sdk/commit/f1f7d218dc78eb1eae41b2cfa5df268ac23be5f6
